const SUPABASE_URL  = 'https://ngtkghhjkdrwcxavktxu.supabase.co';
const SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ndGtnaGhqa2Ryd2N4YXZrdHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk5MTkxNjAsImV4cCI6MjA5NTQ5NTE2MH0.MB3RlA5iFdd1PB62ftx6pqfkucZTNbBnpQ_641G86I0';
const psyncDB = supabase.createClient(SUPABASE_URL, SUPABASE_ANON);
